site_name: Combustion Qualifier Study Guide
nav:
  - Intro: index.md
  - Thermodynamics:
      - Overview: thermo/section1.md
      - Classical Thermodynamics:
          - Classical Thermodynamics for Compressible Substances: thermo/section2.md
      - Quantum and Statistical Mechanics:
          - Chemical Thermodynamics: thermo/section3.md
          - Quantum Theory and Wave Mechanics: thermo/section4.md
          - Statistical Mechanics: thermo/section5.md
          - Statistical Thermodynamics and Thermodynamic Properties: thermo/section6.md
      - Kinetic Theory:
          - Introductory Kinetic Theory: thermo/section7.md
          - Equilibrium Kinetic Theory: thermo/section8.md
      - Review: thermo/review.md
  - Combustion:
      - Introduction and Thermodynamics Review: comb/section1.md
      - Chemical Kinetics and Reaction Mechanisms:
        - Chemical Kinetics: comb/section2.md
        - Coupled Chemical and Thermal Analysis: comb/section3.md
        - Conservation Equations for Multi-Component, Reacting Fluids: comb/section4.md
      - Combustion Waves:
        - Premixed Combustion 1-d Combustion Waves: comb/section5.md
        - Planar Detonation: comb/section6.md
      - Laminar and Nonpremixed Combustion:
        - Laminar Premixed Flames: comb/section7.md
        - Ignition: comb/section8.md
        - Laminar Nonpremixed Combustion: comb/section9.md
      - Turbulent Combustion:
        - Introduction to Turbulent Combustion: comb/section10.md
      - Review: comb/review.md
  - About: about.md

theme:
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.integrate
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep orange

plugins:
  - search
  - charts

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6


# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
# windmill-dark